import { Mouza, LandRecordInput } from "./types";

export const INITIAL_MOUZAS: Mouza[] = [
  {
    id: "mouza_mazina",
    nameBn: "মাঝিনা",
    nameEn: "Mazina",
    districtBn: "গাজীপুর",
    districtEn: "Gazipur",
    upazilaBn: "কালীগঞ্জ",
    upazilaEn: "Kaliganj"
  },
  {
    id: "mouza_bhawal",
    nameBn: "ভাওয়াল",
    nameEn: "Bhawal",
    districtBn: "গাজীপুর",
    districtEn: "Gazipur",
    upazilaBn: "গাজীপুর সদর",
    upazilaEn: "Gazipur Sadar"
  },
  {
    id: "mouza_sreepur",
    nameBn: "শ্রীপুর",
    nameEn: "Sreepur",
    districtBn: "গাজীপুর",
    districtEn: "Gazipur",
    upazilaBn: "শ্রীপুর",
    upazilaEn: "Sreepur"
  }
];

export const SEED_RECORDS: (LandRecordInput & { id: string })[] = [
  {
    id: "seed_record_1",
    mouzaId: "mouza_mazina",
    serialNo: "1",
    fileNo: "1",
    donorName: "এস এম শওকত আলী",
    deedNo: "29810",
    deedType: "সাব কবলা কোং",
    landAmount: "4.30",
    khatianCS: "-",
    khatianSA: "114",
    khatianRS: "294",
    khatianBS: "-",
    khatianNamjari: "-",
    khatianWCL: "1963",
    dagCS: "868",
    dagSA: "868",
    dagRS: "1026",
    dagBS: "-",
    jlCS: "126",
    jlSA: "126",
    jlRS: "125",
    mutationCompany: "WCL",
    mutationIndividual: "-",
    mutationDonor: "-",
    taxYear: "2022-23 (1430)",
    warishCertificate: "02 টি",
    bayaDeed: "-",
    holdingNo: "1962",
    deedRegDate: "11/11/2009",
    mediaName: "-",
    remarks: "মূল দলিল",
    caseNo: "-"
  },
  {
    id: "seed_record_2",
    mouzaId: "mouza_mazina",
    serialNo: "2",
    fileNo: "1",
    donorName: "আব্দুর রহমান মৃধা",
    deedNo: "15432",
    deedType: "হেবা বিল এওয়াজ",
    landAmount: "1.25",
    khatianCS: "85",
    khatianSA: "92",
    khatianRS: "120",
    khatianBS: "145",
    khatianNamjari: "202/ক",
    khatianWCL: "-",
    dagCS: "412",
    dagSA: "412",
    dagRS: "489",
    dagBS: "512",
    jlCS: "126",
    jlSA: "126",
    jlRS: "125",
    mutationCompany: "-",
    mutationIndividual: "আব্দুর রহমান",
    mutationDonor: "-",
    taxYear: "2023-24 (1431)",
    warishCertificate: "-",
    bayaDeed: "দলিল নং ৪৩২১ (১৯৯৮)",
    holdingNo: "884",
    deedRegDate: "05/06/2012",
    mediaName: "মফিজ উদ্দিন",
    remarks: "নকল দলিল সংযুক্ত",
    caseNo: "২০২/২০১২-১৩"
  },
  {
    id: "seed_record_3",
    mouzaId: "mouza_bhawal",
    serialNo: "1",
    fileNo: "4",
    donorName: "মোছাম্মৎ মরিয়ম বেগম",
    deedNo: "8765",
    deedType: "দানপত্র",
    landAmount: "2.10",
    khatianCS: "210",
    khatianSA: "245",
    khatianRS: "312",
    khatianBS: "-",
    khatianNamjari: "45/খ",
    khatianWCL: "-",
    dagCS: "1054",
    dagSA: "1054",
    dagRS: "1240",
    dagBS: "-",
    jlCS: "80",
    jlSA: "80",
    jlRS: "80",
    mutationCompany: "-",
    mutationIndividual: "مরিয়ম বেগম",
    mutationDonor: "মৃত আকবর আলী",
    taxYear: "2022-23",
    warishCertificate: "০১ টি",
    bayaDeed: "-",
    holdingNo: "1205",
    deedRegDate: "21/03/2015",
    mediaName: "-",
    remarks: "মূল দলিল নিখোঁজ (জিডি নং ৪১২)",
    caseNo: "৪৫/২০১৫"
  }
];
